---
name: Code Unit tests

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test:
    # Name the Job
    name: Code Unit Test
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flac libflac-dev

      # update submodules
      - name: Git Submodule Update
        run: |

          git submodule update --init --recursive

      # Runs the Super-Linter action
      - name: Compile and run tests
        run: make test
